esphome:
  name: esp32-passthrough
  friendly_name: ESP32 Audio Bridge

# Standard ESP32 (non-S3) acting as an I2S slave/master bridge.
# Receives I2S audio from the ESP32-S3 Sendspin device and retransmits
# it to an external DAC as I2S master.
esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO
  logs:
    I2S_BRIDGE: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESP32-Bridge-Fallback"
    password: "12345678"

web_server:
  port: 80

# DAC mute control — GPIO32 drives the DAC's unmute/enable pin.
# Kept on at all times; the bridge task disables the TX channel instead of
# toggling this pin when the audio signal is lost.
switch:
  - platform: gpio
    id: dac_unmute
    name: "DAC Unmute"
    pin:
      number: GPIO32
      mode:
        output: true
    restore_mode: RESTORE_DEFAULT_ON

# The i2s_passthrough component is a local custom component that implements
# the RX (slave) -> TX (master) bridge loop in a dedicated FreeRTOS task.
external_components:
  - source:
      type: local
      path: ./esphome_components

i2s_passthrough: